// File: KanbanCardModal.jsx
import React, { useState, useEffect } from "react";
import { injectConfig } from "../ai/securityUtils.js";
import CrewAssignmentModal from "./CrewAssignmentModal";

export default function KanbanCardModal({ card, closeModal, updateCards, lanes, statuses }) {
  const [localCard, setLocalCard] = useState({ ...card });
  const [crewAssignmentOpen, setCrewAssignmentOpen] = useState(false);
  const [pendingScheduledDate, setPendingScheduledDate] = useState('');
  const [availableVendors, setAvailableVendors] = useState([]);
  const [availablePersonnel, setAvailablePersonnel] = useState([]);
  const [newComment, setNewComment] = useState('');
  const [autoSaveTimeout, setAutoSaveTimeout] = useState(null);
  const [smartSuggestions, setSmartSuggestions] = useState({});
  const [autoGeneratedFields, setAutoGeneratedFields] = useState({});
  const [intelligentSuggestions, setIntelligentSuggestions] = useState({});
  const [projectPredictions, setProjectPredictions] = useState({});

  useEffect(() => {
    setLocalCard({ ...card });
    generateSmartDefaults({ ...card });
  }, [card]);

  // Smart defaults and auto-population system
  const generateSmartDefaults = (cardData) => {
    const suggestions = {};
    const autoFields = {};

    // Auto-generate job number if not set
    if (!cardData.jobNumber && cardData.location) {
      autoFields.jobNumber = generateJobNumber(cardData.location);
    }

    // Suggest customer info based on previous projects
    if (cardData.customerName) {
      const customerSuggestions = getCustomerSuggestions(cardData.customerName);
      if (customerSuggestions) {
        suggestions.customerLocation = customerSuggestions.location;
        suggestions.revenue = customerSuggestions.avgRevenue;
        suggestions.vendor = customerSuggestions.preferredVendor;
      }
    }

    // Auto-set priority based on keywords
    if (cardData.title && !cardData.priority) {
      autoFields.priority = detectPriorityFromTitle(cardData.title);
    }

    // Auto-suggest vendors based on location and project type
    if (cardData.location) {
      suggestions.recommendedVendors = getLocationVendors(cardData.location);
    }

    setSmartSuggestions(suggestions);
    setAutoGeneratedFields(autoFields);

    // Apply auto-generated fields
    if (Object.keys(autoFields).length > 0) {
      setLocalCard(prev => ({ ...prev, ...autoFields }));
    }

    // Generate intelligent predictions
    generateIntelligentPredictions(cardData);
  };

  // Intelligent data inference system
  const generateIntelligentPredictions = (cardData) => {
    const predictions = {};
    const existingCards = JSON.parse(localStorage.getItem('kanban_cards') || '[]');

    // Always provide basic industry insights even without historical data
    if (!cardData.id || existingCards.length < 3) {
      predictions.industryInsights = getIndustryInsights(cardData);
    }

    // Predict completion timeline based on similar projects
    if (cardData.status && cardData.location) {
      const similarProjects = existingCards.filter(c =>
        c.status === cardData.status &&
        c.location === cardData.location &&
        c.statusHistory &&
        c.statusHistory.length > 1
      );

      if (similarProjects.length > 0) {
        predictions.estimatedDuration = predictProjectDuration(similarProjects);
        predictions.nextMilestone = predictNextMilestone(cardData, similarProjects);
      }
    }

    // Predict revenue based on project characteristics
    if (cardData.customerName || cardData.title) {
      predictions.estimatedRevenue = predictRevenue(cardData, existingCards);
    }

    // Predict required vendors based on project type
    if (cardData.title) {
      predictions.suggestedVendors = predictRequiredVendors(cardData.title, existingCards);
    }

    // Predict potential issues based on patterns
    predictions.potentialRisks = identifyPotentialRisks(cardData, existingCards);

    // Predict optimal assignment based on workload and expertise
    predictions.recommendedAssignment = predictOptimalAssignment(cardData, existingCards);

    setIntelligentSuggestions(predictions);
    setProjectPredictions(predictions);
  };

  // Industry insights for new projects
  const getIndustryInsights = (cardData) => {
    const insights = {
      suggestedDuration: null,
      budgetRange: null,
      commonChallenges: [],
      requiredPermits: [],
      safetyConsiderations: []
    };

    const title = (cardData.title || '').toLowerCase();

    // Environmental project insights
    if (title.includes('lab') || title.includes('chemical') || title.includes('waste')) {
      insights.suggestedDuration = { min: 5, max: 14, unit: 'days' };
      insights.budgetRange = { min: 2000, max: 15000 };
      insights.commonChallenges = ['Proper chemical segregation', 'Transportation permits', 'Disposal facility availability'];
      insights.requiredPermits = ['Waste transporter license', 'EPA manifest'];
      insights.safetyConsiderations = ['PPE requirements', 'Chemical compatibility', 'Spill containment'];
    } else if (title.includes('tank') || title.includes('clean')) {
      insights.suggestedDuration = { min: 3, max: 10, unit: 'days' };
      insights.budgetRange = { min: 5000, max: 25000 };
      insights.commonChallenges = ['Confined space entry', 'Residual contamination', 'Equipment access'];
      insights.requiredPermits = ['Confined space permit', 'Hot work permit'];
      insights.safetyConsiderations = ['Gas monitoring', 'Rescue standby', 'Ventilation systems'];
    } else if (title.includes('soil') || title.includes('remediation')) {
      insights.suggestedDuration = { min: 30, max: 120, unit: 'days' };
      insights.budgetRange = { min: 15000, max: 100000 };
      insights.commonChallenges = ['Contamination extent', 'Regulatory approval', 'Weather dependency'];
      insights.requiredPermits = ['Excavation permits', 'State environmental approval'];
      insights.safetyConsiderations = ['Soil sampling', 'Air monitoring', 'Equipment decontamination'];
    } else if (title.includes('asbestos')) {
      insights.suggestedDuration = { min: 5, max: 15, unit: 'days' };
      insights.budgetRange = { min: 10000, max: 50000 };
      insights.commonChallenges = ['Containment setup', 'Air monitoring', 'Licensed disposal'];
      insights.requiredPermits = ['Asbestos removal license', 'Air quality permits'];
      insights.safetyConsiderations = ['Negative pressure', 'Personal monitoring', 'Decontamination procedures'];
    } else if (title.includes('emergency') || title.includes('spill')) {
      insights.suggestedDuration = { min: 1, max: 3, unit: 'days' };
      insights.budgetRange = { min: 3000, max: 20000 };
      insights.commonChallenges = ['Response time', 'Environmental impact', 'Regulatory notification'];
      insights.requiredPermits = ['Emergency response authorization'];
      insights.safetyConsiderations = ['Site safety', 'Personnel protection', 'Public safety'];
    }

    return insights;
  };

  // Predict project duration based on historical data
  const predictProjectDuration = (similarProjects) => {
    const durations = similarProjects.map(project => {
      const created = new Date(project.created);
      const completed = project.statusHistory.find(h =>
        h.status && (
          h.status.toLowerCase().includes('complete') ||
          h.status.toLowerCase().includes('finished') ||
          h.status.toLowerCase().includes('done')
        )
      );

      if (completed) {
        const completedDate = new Date(completed.timestamp);
        return Math.floor((completedDate - created) / (1000 * 60 * 60 * 24));
      }
      return null;
    }).filter(d => d !== null);

    if (durations.length === 0) return null;

    const avgDuration = durations.reduce((a, b) => a + b, 0) / durations.length;
    const confidence = durations.length >= 3 ? 'high' : durations.length >= 2 ? 'medium' : 'low';

    return {
      days: Math.round(avgDuration),
      confidence,
      sampleSize: durations.length
    };
  };

  // Predict next milestone
  const predictNextMilestone = (currentCard, similarProjects) => {
    const currentStatus = currentCard.status;
    const nextStatusTransitions = {};

    similarProjects.forEach(project => {
      const statusHistory = project.statusHistory || [];
      for (let i = 0; i < statusHistory.length - 1; i++) {
        const current = statusHistory[i].status;
        const next = statusHistory[i + 1].status;
        if (current === currentStatus) {
          nextStatusTransitions[next] = (nextStatusTransitions[next] || 0) + 1;
        }
      }
    });

    const mostLikelyNext = Object.entries(nextStatusTransitions)
      .sort((a, b) => b[1] - a[1])[0];

    if (mostLikelyNext) {
      return {
        status: mostLikelyNext[0],
        probability: (mostLikelyNext[1] / similarProjects.length * 100).toFixed(0)
      };
    }
    return null;
  };

  // Predict revenue based on similar projects
  const predictRevenue = (cardData, existingCards) => {
    const projectKeywords = (cardData.title || '').toLowerCase().split(' ');
    const customerProjects = existingCards.filter(c =>
      c.customerName === cardData.customerName ||
      projectKeywords.some(keyword =>
        keyword.length > 3 && (c.title || '').toLowerCase().includes(keyword)
      )
    );

    const revenues = customerProjects
      .map(c => parseFloat(c.revenue || 0))
      .filter(r => r > 0);

    if (revenues.length === 0) return null;

    const avgRevenue = revenues.reduce((a, b) => a + b, 0) / revenues.length;
    const minRevenue = Math.min(...revenues);
    const maxRevenue = Math.max(...revenues);

    return {
      estimated: Math.round(avgRevenue),
      range: { min: minRevenue, max: maxRevenue },
      confidence: revenues.length >= 3 ? 'high' : 'medium',
      sampleSize: revenues.length
    };
  };

  // Predict required vendors based on project type
  const predictRequiredVendors = (title, existingCards) => {
    const keywords = title.toLowerCase().split(' ');
    const vendorFrequency = {};

    existingCards.forEach(card => {
      if (card.vendors && keywords.some(keyword =>
        keyword.length > 3 && (card.title || '').toLowerCase().includes(keyword)
      )) {
        card.vendors.forEach(vendor => {
          if (vendor.name) {
            vendorFrequency[vendor.name] = (vendorFrequency[vendor.name] || 0) + 1;
          }
        });
      }
    });

    return Object.entries(vendorFrequency)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([name, frequency]) => ({ name, frequency }));
  };

  // Identify potential risks based on patterns
  const identifyPotentialRisks = (cardData, existingCards) => {
    const risks = [];

    // Check for customers with delayed payment history
    if (cardData.customerName) {
      const customerProjects = existingCards.filter(c =>
        c.customerName === cardData.customerName &&
        c.statusHistory
      );

      const avgDuration = customerProjects.reduce((total, project) => {
        const created = new Date(project.created);
        const lastUpdate = new Date(project.updated || project.created);
        return total + (lastUpdate - created) / (1000 * 60 * 60 * 24);
      }, 0) / (customerProjects.length || 1);

      if (avgDuration > 45) {
        risks.push({
          type: 'customer_delay',
          message: 'Customer has history of delayed projects',
          severity: 'medium'
        });
      }
    }

    // Check for location capacity issues
    if (cardData.location) {
      const activeProjectsInLocation = existingCards.filter(c =>
        c.location === cardData.location &&
        c.status &&
        !c.status.toLowerCase().includes('complete')
      ).length;

      if (activeProjectsInLocation > 5) {
        risks.push({
          type: 'capacity_risk',
          message: `High workload in ${cardData.location} (${activeProjectsInLocation} active projects)`,
          severity: 'high'
        });
      }
    }

    // Check for seasonal patterns
    const month = new Date().getMonth();
    const seasonalData = existingCards.filter(c => {
      const cardMonth = new Date(c.created).getMonth();
      return Math.abs(cardMonth - month) <= 1;
    });

    if (seasonalData.length > existingCards.length * 0.3) {
      risks.push({
        type: 'seasonal_peak',
        message: 'High activity period - consider resource planning',
        severity: 'low'
      });
    }

    return risks;
  };

  // Predict optimal assignment
  const predictOptimalAssignment = (cardData, existingCards) => {
    const assignmentPerformance = {};

    existingCards.forEach(card => {
      if (card.assignedTo && card.statusHistory) {
        const duration = Math.floor(
          (new Date(card.updated || card.created) - new Date(card.created)) / (1000 * 60 * 60 * 24)
        );
        const isCompleted = card.status && card.status.toLowerCase().includes('complete');

        if (!assignmentPerformance[card.assignedTo]) {
          assignmentPerformance[card.assignedTo] = {
            totalProjects: 0,
            completedProjects: 0,
            avgDuration: 0,
            totalDuration: 0
          };
        }

        const perf = assignmentPerformance[card.assignedTo];
        perf.totalProjects++;
        perf.totalDuration += duration;
        perf.avgDuration = perf.totalDuration / perf.totalProjects;

        if (isCompleted) {
          perf.completedProjects++;
        }
      }
    });

    // Calculate efficiency scores
    const recommendations = Object.entries(assignmentPerformance)
      .map(([person, perf]) => ({
        person,
        completionRate: (perf.completedProjects / perf.totalProjects * 100).toFixed(1),
        avgDuration: perf.avgDuration.toFixed(1),
        efficiency: (perf.completedProjects / perf.avgDuration * 100).toFixed(1),
        totalProjects: perf.totalProjects
      }))
      .sort((a, b) => parseFloat(b.efficiency) - parseFloat(a.efficiency))
      .slice(0, 3);

    return recommendations;
  };

  // Generate job number: LocationYearPeriodSequence
  const generateJobNumber = (location) => {
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth() + 1;
    const period = Math.ceil(month / 3); // Q1, Q2, Q3, Q4

    // Get location prefix (first 3 letters)
    const locationPrefix = location.substring(0, 3).toUpperCase();

    // Get existing cards to determine sequence
    const existingCards = JSON.parse(localStorage.getItem('kanban_cards') || '[]');
    const sameLocationCards = existingCards.filter(c =>
      c.jobNumber && c.jobNumber.startsWith(`${locationPrefix}${year}P${period}`)
    );

    const sequence = String(sameLocationCards.length + 1).padStart(2, '0');
    return `${locationPrefix}${year}P${period}${sequence}`;
  };

  // Detect priority from title keywords
  const detectPriorityFromTitle = (title) => {
    const lowerTitle = title.toLowerCase();
    if (lowerTitle.includes('emergency') || lowerTitle.includes('urgent') || lowerTitle.includes('asap')) {
      return 'Critical';
    }
    if (lowerTitle.includes('rush') || lowerTitle.includes('priority') || lowerTitle.includes('expedite')) {
      return 'High';
    }
    if (lowerTitle.includes('routine') || lowerTitle.includes('standard') || lowerTitle.includes('regular')) {
      return 'Low';
    }
    return 'Medium';
  };

  // Get customer suggestions from previous projects
  const getCustomerSuggestions = (customerName) => {
    const existingCards = JSON.parse(localStorage.getItem('kanban_cards') || '[]');
    const customerProjects = existingCards.filter(c =>
      c.customerName && c.customerName.toLowerCase() === customerName.toLowerCase()
    );

    if (customerProjects.length === 0) return null;

    // Get most common location
    const locations = customerProjects.map(c => c.customerLocation).filter(Boolean);
    const mostCommonLocation = locations.sort((a,b) =>
      locations.filter(v => v === a).length - locations.filter(v => v === b).length
    ).pop();

    // Calculate average revenue
    const revenues = customerProjects.map(c => parseFloat(c.revenue || 0)).filter(r => r > 0);
    const avgRevenue = revenues.length > 0 ? Math.round(revenues.reduce((a, b) => a + b, 0) / revenues.length) : null;

    // Get most used vendor
    const vendors = customerProjects.map(c => c.vendor).filter(Boolean);
    const preferredVendor = vendors.sort((a,b) =>
      vendors.filter(v => v === a).length - vendors.filter(v => v === b).length
    ).pop();

    return {
      location: mostCommonLocation,
      avgRevenue,
      preferredVendor
    };
  };

  // Get recommended vendors for location
  const getLocationVendors = (location) => {
    const storedVendors = localStorage.getItem('kanban_vendors');
    if (!storedVendors) return [];

    const vendors = JSON.parse(storedVendors);
    return vendors.filter(vendor =>
      vendor.active && (
        vendor.location === location ||
        vendor.location === 'Regional' ||
        vendor.serviceAreas?.includes(location)
      )
    ).slice(0, 3); // Top 3 recommendations
  };

  // Load vendors and personnel when modal opens
  useEffect(() => {
    const storedVendors = localStorage.getItem('kanban_vendors');
    if (storedVendors) {
      const vendors = JSON.parse(storedVendors);
      setAvailableVendors(vendors.filter(vendor => vendor.active));
    }

    const storedPersonnel = localStorage.getItem('kanban_personnel');
    if (storedPersonnel) {
      const personnel = JSON.parse(storedPersonnel);
      // Filter to show only Regional personnel and personnel for this specific location
      const filteredPersonnel = personnel.filter(person =>
        person.active && (
          person.location === 'Regional' ||
          person.location === localCard.location
        )
      );
      setAvailablePersonnel(filteredPersonnel);
    }
  }, []);

  // Update personnel list when location changes
  useEffect(() => {
    const storedPersonnel = localStorage.getItem('kanban_personnel');
    if (storedPersonnel) {
      const personnel = JSON.parse(storedPersonnel);
      // Filter to show only Regional personnel and personnel for this specific location
      const filteredPersonnel = personnel.filter(person =>
        person.active && (
          person.location === 'Regional' ||
          person.location === localCard.location
        )
      );
      setAvailablePersonnel(filteredPersonnel);
    }
  }, [localCard.location]);

  // Apply smart suggestion
  const applySuggestion = (field, value) => {
    setLocalCard(prev => ({ ...prev, [field]: value }));

    // Add comment about auto-fill
    const comments = localCard.comments || [];
    const newComment = {
      id: Date.now(),
      text: `🤖 Auto-filled ${field}: ${value} (based on previous data)`,
      timestamp: new Date().toISOString(),
      author: 'System',
      type: 'auto-fill'
    };

    setLocalCard(prev => ({
      ...prev,
      comments: [...comments, newComment]
    }));
  };

  const handleChange = (field, value) => {
    // Trigger smart suggestions when certain fields change
    if (field === 'customerName' && value) {
      setTimeout(() => generateSmartDefaults({ ...localCard, [field]: value }), 100);
    }
    if (field === 'location' && value) {
      setTimeout(() => generateSmartDefaults({ ...localCard, [field]: value }), 100);
    }
    if (field === 'status') {
      // Track chronological status updates with enhanced timeline
      const statusHistory = localCard.statusHistory || [];
      const statusTimeline = localCard.statusTimeline || {};
      const currentDate = new Date().toISOString();

      const newStatusEntry = {
        status: value,
        timestamp: currentDate,
        previousStatus: localCard.status || 'New'
      };

      // Update status timeline with key milestones
      const updatedTimeline = { ...statusTimeline };

      // Track specific milestone dates and add automated comments
      let milestoneComment = null;
      if (value.toLowerCase().includes('lead')) {
        if (!updatedTimeline.dateReceived) {
          updatedTimeline.dateReceived = currentDate;
          milestoneComment = '📅 Date Received milestone auto-set based on Lead status';
        }
      } else if (value.toLowerCase().includes('quote')) {
        updatedTimeline.quoteSent = currentDate;
        milestoneComment = '📅 Quote Sent milestone auto-set based on Quoted status';
      } else if (value.toLowerCase().includes('scheduled') || value.toLowerCase().includes('contracted') || value.toLowerCase().includes('active')) {
        updatedTimeline.dateScheduled = currentDate;
        milestoneComment = '📅 Date Scheduled milestone auto-set based on status change';
      } else if (value.toLowerCase().includes('complete') || value.toLowerCase().includes('finished') || value.toLowerCase().includes('done')) {
        updatedTimeline.dateComplete = currentDate;
        milestoneComment = '📅 Date Complete milestone auto-set based on completion status';
      }

      // Clear revenue if changing to Lead status
      const updatedCard = {
        ...localCard,
        [field]: value,
        statusHistory: [...statusHistory, newStatusEntry],
        statusTimeline: updatedTimeline,
        updated: currentDate
      };

      if (value === 'Lead') {
        updatedCard.revenue = '';
        // Also clear vendor revenues
        if (updatedCard.vendors) {
          updatedCard.vendors = updatedCard.vendors.map(vendor => ({
            ...vendor,
            revenue: ''
          }));
        }
      }

      // Prompt for estimated PO amount when status changes to "Quoted"
      if (value.toLowerCase().includes('quoted') && !localCard.estimatedPOAmount) {
        setTimeout(() => {
          const poAmount = prompt('This job is now quoted. Please enter the estimated total PO amount for vendor costs:');
          if (poAmount && !isNaN(parseFloat(poAmount))) {
            setLocalCard(prev => ({
              ...prev,
              estimatedPOAmount: parseFloat(poAmount)
            }));
          }
        }, 100);
      }

      // Add milestone comment if one was auto-generated
      if (milestoneComment) {
        const comments = updatedCard.comments || [];
        const newComment = {
          id: Date.now() + 1, // +1 to avoid collision with status change comment
          text: milestoneComment,
          timestamp: currentDate,
          author: 'System',
          type: 'milestone'
        };
        updatedCard.comments = [...comments, newComment];
      }

      setLocalCard(updatedCard);
    } else if (field === 'scheduledDate') {
      // If a scheduled date is being set and we don't have crew assigned, open crew modal
      if (value && !localCard.assignedCrew?.length) {
        setPendingScheduledDate(value);
        setLocalCard(prev => ({ ...prev, [field]: value }));
        setCrewAssignmentOpen(true);
      } else {
        setLocalCard(prev => ({ ...prev, [field]: value }));
      }
    } else {
      setLocalCard(prev => ({ ...prev, [field]: value }));
    }
  };

  const handleSave = () => {
    // Always update the 'updated' timestamp when saving
    const cardToSave = {
      ...localCard,
      updated: new Date().toISOString()
    };
    updateCards(cardToSave);
    closeModal();
  };

  const handleFileUpload = (e) => {
    const files = Array.from(e.target.files);
    files.forEach(file => {
      const reader = new FileReader();
      reader.onload = () => {
        const newAttachment = {
          name: file.name,
          url: reader.result,
          type: 'general',
          uploadDate: new Date().toISOString()
        };
        setLocalCard(prev => ({
          ...prev,
          attachments: [...(prev.attachments || []), newAttachment],
        }));
      };
      reader.readAsDataURL(file);
    });
  };

  // Enhanced document upload with intelligent parsing and project linking
  const handleCategorizedFileUpload = (e, category) => {
    const files = Array.from(e.target.files);
    files.forEach(file => {
      const reader = new FileReader();
      reader.onload = () => {
        // Enhanced document analysis
        parseDocumentContent(file, reader.result, category)
          .then(parsedData => {
            const newAttachment = {
              name: file.name,
              url: reader.result,
              type: category,
              uploadDate: new Date().toISOString(),
              scanResults: parsedData.scanResults,
              extractedData: parsedData.extractedData,
              confidence: parsedData.confidence
            };

            setLocalCard(prev => {
              let updates = { attachments: [...(prev.attachments || []), newAttachment] };

              // Auto-populate fields based on extracted data
              if (parsedData.extractedData) {
                const extracted = parsedData.extractedData;

                // Customer information
                if (extracted.customerName && !prev.customerName) {
                  updates.customerName = extracted.customerName;
                }
                if (extracted.customerAddress && !prev.customerLocation) {
                  updates.customerLocation = extracted.customerAddress;
                }

                // Project details
                if (extracted.projectTitle && !prev.title) {
                  updates.title = extracted.projectTitle;
                }
                if (extracted.jobNumber && !prev.jobNumber) {
                  updates.jobNumber = extracted.jobNumber;
                }

                // Financial information
                if (extracted.totalAmount && !prev.revenue) {
                  updates.revenue = extracted.totalAmount;
                }
                if (extracted.vendorAmount && category === 'vendorQuote') {
                  updates.estimatedPOAmount = extracted.vendorAmount;
                }

                // Dates and scheduling
                if (extracted.scheduledDate && !prev.scheduledDate) {
                  updates.scheduledDate = extracted.scheduledDate;
                }
                if (extracted.dueDate && !prev.dueDate) {
                  updates.dueDate = extracted.dueDate;
                }

                // Auto-detect project type and set priority
                if (extracted.projectType) {
                  if (extracted.projectType.includes('emergency') || extracted.priority === 'urgent') {
                    updates.priority = 'Critical';
                  } else if (extracted.projectType.includes('routine')) {
                    updates.priority = 'Medium';
                  }
                }

                // Vendor information
                if (extracted.vendorInfo && category === 'vendorQuote') {
                  const existingVendors = prev.vendors || [];
                  const newVendor = {
                    id: Date.now(),
                    name: extracted.vendorInfo.name || 'Vendor from document',
                    estimate: extracted.vendorInfo.amount || extracted.vendorAmount || '',
                    poNumber: extracted.vendorInfo.poNumber || '',
                    contactInfo: extracted.vendorInfo.contact || '',
                    notes: `Auto-added from ${file.name}`
                  };
                  updates.vendors = [...existingVendors, newVendor];
                }

                // Status updates based on document type
                if (category === 'signedQuote' && extracted.signed) {
                  const contractedStatus = statuses.find(s =>
                    s.name.toLowerCase().includes('contract') ||
                    s.name.toLowerCase().includes('scheduled')
                  );
                  if (contractedStatus) {
                    updates.status = contractedStatus.name;
                  }
                }
              }

              // Check for existing project matches
              const projectMatch = findMatchingProject(parsedData.extractedData);
              if (projectMatch && projectMatch.id !== prev.id) {
                // Document might belong to a different project
                updates.suggestedProjectLink = {
                  projectId: projectMatch.id,
                  projectTitle: projectMatch.title,
                  customerName: projectMatch.customerName,
                  confidence: projectMatch.matchConfidence
                };
              }

              // Add automated comment about the extraction
              const comments = prev.comments || [];
              const extractionComment = {
                id: Date.now() + Math.random(),
                text: generateExtractionComment(parsedData, file.name, category, projectMatch),
                timestamp: new Date().toISOString(),
                author: 'System',
                type: 'document-analysis'
              };
              updates.comments = [...comments, extractionComment];

              return { ...prev, ...updates };
            });
          })
          .catch(error => {
            console.error('Document parsing error:', error);
            // Fallback to basic scanning
            const basicScanResults = scanDocument(file.name, category);
            const newAttachment = {
              name: file.name,
              url: reader.result,
              type: category,
              uploadDate: new Date().toISOString(),
              scanResults: basicScanResults
            };

            setLocalCard(prev => ({
              ...prev,
              attachments: [...(prev.attachments || []), newAttachment]
            }));
          });
      };

      // For text files, read as text; for others, read as data URL
      if (file.type.startsWith('text/') || file.name.endsWith('.txt')) {
        reader.readAsText(file);
      } else {
        reader.readAsDataURL(file);
      }
    });
  };

  // Advanced document parsing with content analysis
  const parseDocumentContent = async (file, content, category) => {
    const filename = file.name.toLowerCase();
    let extractedData = {};
    let confidence = 'low';
    let text = '';

    try {
      // Extract text based on file type
      if (file.type.startsWith('text/') || filename.endsWith('.txt')) {
        text = content;
      } else if (filename.endsWith('.csv')) {
        text = content;
      } else {
        // For PDFs and images, we'll do basic pattern matching on filename
        // In a real implementation, you'd use PDF.js or OCR libraries
        text = filename;
      }

      // Intelligent text parsing
      const patterns = {
        // Customer information patterns
        customerName: [
          /(?:customer|client|company)\s*:?\s*([A-Za-z\s&.,'-]+?)(?:\n|,|\.|$)/gi,
          /bill\s+to\s*:?\s*([A-Za-z\s&.,'-]+?)(?:\n|,|\.|$)/gi,
          /^([A-Z][A-Za-z\s&.,'-]+)(?:\n|,)/gm
        ],
        // Project information
        projectTitle: [
          /(?:project|job|work)\s*:?\s*([A-Za-z\s-]+?)(?:\n|,|\.|$)/gi,
          /(?:description|scope)\s*:?\s*([A-Za-z\s-]+?)(?:\n|,|\.|$)/gi
        ],
        jobNumber: [
          /(?:job|project|po|order)\s*#?\s*:?\s*([A-Z0-9-]+)/gi,
          /\b([A-Z]{2,3}\d{4}[A-Z]?\d{2,4})\b/gi
        ],
        // Financial information
        totalAmount: [
          /(?:total|amount|cost|price)\s*:?\s*\$?([\d,]+\.?\d*)/gi,
          /\$([\d,]+\.?\d*)/g
        ],
        vendorAmount: [
          /(?:vendor|contractor|estimate)\s*:?\s*\$?([\d,]+\.?\d*)/gi
        ],
        // Dates
        scheduledDate: [
          /(?:scheduled|start|begin)\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{2,4})/gi,
          /(?:scheduled|start|begin)\s*:?\s*(\d{1,2}-\d{1,2}-\d{2,4})/gi
        ],
        dueDate: [
          /(?:due|completion|end)\s*:?\s*(\d{1,2}\/\d{1,2}\/\d{2,4})/gi,
          /(?:due|completion|end)\s*:?\s*(\d{1,2}-\d{1,2}-\d{2,4})/gi
        ],
        // Address information
        address: [
          /(?:address|location|site)\s*:?\s*([A-Za-z0-9\s,.-]+?)(?:\n|zip|state)/gi
        ],
        // Contact information
        phone: [
          /(?:phone|tel|mobile)\s*:?\s*([\d\s\(\)\-\.]+)/gi,
          /\b(\d{3}[\s\-\.]?\d{3}[\s\-\.]?\d{4})\b/g
        ],
        email: [
          /([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/g
        ]
      };

      // Extract data using patterns
      for (const [field, regexArray] of Object.entries(patterns)) {
        for (const regex of regexArray) {
          const matches = [...text.matchAll(regex)];
          if (matches.length > 0) {
            let value = matches[0][1]?.trim();
            if (value) {
              // Clean up extracted values
              if (field.includes('Amount') || field === 'revenue') {
                value = value.replace(/,/g, '');
                if (!isNaN(parseFloat(value))) {
                  extractedData[field] = parseFloat(value);
                  confidence = 'high';
                }
              } else if (field.includes('Date')) {
                // Normalize date format
                extractedData[field] = normalizeDate(value);
                confidence = 'high';
              } else {
                extractedData[field] = value;
                confidence = 'medium';
              }
              break;
            }
          }
        }
      }

      // Enhanced document type detection
      const documentAnalysis = analyzeDocumentType(text, filename, category);
      extractedData = { ...extractedData, ...documentAnalysis };

      // Vendor information extraction for quotes
      if (category === 'vendorQuote' || category === 'customerQuote') {
        const vendorInfo = extractVendorInfo(text);
        if (vendorInfo) {
          extractedData.vendorInfo = vendorInfo;
        }
      }

      // Project type classification
      extractedData.projectType = classifyProjectType(text);

    } catch (error) {
      console.error('Text parsing error:', error);
    }

    return {
      extractedData,
      confidence,
      scanResults: scanDocument(file.name, category)
    };
  };

  // Helper function to normalize dates
  const normalizeDate = (dateStr) => {
    try {
      const date = new Date(dateStr);
      return date.toISOString().split('T')[0]; // Return YYYY-MM-DD format
    } catch {
      return dateStr;
    }
  };

  // Enhanced document type analysis
  const analyzeDocumentType = (text, filename, category) => {
    const analysis = {};
    const lowerText = text.toLowerCase();
    const lowerFilename = filename.toLowerCase();

    // Detect if document is signed
    if (lowerText.includes('signed') || lowerText.includes('signature') ||
        lowerText.includes('executed') || lowerFilename.includes('signed')) {
      analysis.signed = true;
    }

    // Detect urgency/priority
    if (lowerText.includes('urgent') || lowerText.includes('emergency') ||
        lowerText.includes('immediate') || lowerText.includes('asap')) {
      analysis.priority = 'urgent';
    }

    // Detect project phase
    if (lowerText.includes('proposal') || lowerText.includes('estimate')) {
      analysis.phase = 'proposal';
    } else if (lowerText.includes('contract') || lowerText.includes('agreement')) {
      analysis.phase = 'contract';
    } else if (lowerText.includes('invoice') || lowerText.includes('bill')) {
      analysis.phase = 'billing';
    }

    return analysis;
  };

  // Extract vendor information
  const extractVendorInfo = (text) => {
    const vendorPatterns = {
      name: /(?:vendor|contractor|company)\s*:?\s*([A-Za-z\s&.,'-]+)/gi,
      contact: /(?:contact|rep|representative)\s*:?\s*([A-Za-z\s'-]+)/gi,
      amount: /(?:amount|total|cost)\s*:?\s*\$?([\d,]+\.?\d*)/gi,
      poNumber: /(?:po|purchase\s+order)\s*#?\s*:?\s*([A-Z0-9-]+)/gi
    };

    const vendorInfo = {};
    for (const [field, regex] of Object.entries(vendorPatterns)) {
      const match = text.match(regex);
      if (match && match[1]) {
        vendorInfo[field] = match[1].trim();
      }
    }

    return Object.keys(vendorInfo).length > 0 ? vendorInfo : null;
  };

  // Classify project type based on content
  const classifyProjectType = (text) => {
    const lowerText = text.toLowerCase();

    if (lowerText.includes('lab') && (lowerText.includes('pack') || lowerText.includes('chemical'))) {
      return 'lab-pack';
    } else if (lowerText.includes('tank') && lowerText.includes('clean')) {
      return 'tank-cleaning';
    } else if (lowerText.includes('soil') && lowerText.includes('remediation')) {
      return 'soil-remediation';
    } else if (lowerText.includes('asbestos')) {
      return 'asbestos-abatement';
    } else if (lowerText.includes('emergency') || lowerText.includes('spill')) {
      return 'emergency-response';
    } else if (lowerText.includes('waste') && lowerText.includes('disposal')) {
      return 'waste-disposal';
    }

    return 'general';
  };

  // Find matching existing projects
  const findMatchingProject = (extractedData) => {
    const existingCards = JSON.parse(localStorage.getItem('kanban_cards') || '[]');
    let bestMatch = null;
    let highestScore = 0;

    existingCards.forEach(card => {
      let score = 0;
      let matchReasons = [];

      // Job number match (highest priority)
      if (extractedData.jobNumber && card.jobNumber) {
        if (extractedData.jobNumber === card.jobNumber) {
          score += 100;
          matchReasons.push('Job number exact match');
        } else if (extractedData.jobNumber.includes(card.jobNumber) || card.jobNumber.includes(extractedData.jobNumber)) {
          score += 50;
          matchReasons.push('Job number partial match');
        }
      }

      // Customer name match
      if (extractedData.customerName && card.customerName) {
        const customerSimilarity = calculateStringSimilarity(extractedData.customerName, card.customerName);
        if (customerSimilarity > 0.8) {
          score += 40;
          matchReasons.push(`Customer name match (${Math.round(customerSimilarity * 100)}%)`);
        }
      }

      // Project title match
      if (extractedData.projectTitle && card.title) {
        const titleSimilarity = calculateStringSimilarity(extractedData.projectTitle, card.title);
        if (titleSimilarity > 0.6) {
          score += 30;
          matchReasons.push(`Project title match (${Math.round(titleSimilarity * 100)}%)`);
        }
      }

      // Amount match (within 20%)
      if (extractedData.totalAmount && card.revenue) {
        const cardRevenue = parseFloat(card.revenue);
        const docAmount = extractedData.totalAmount;
        const percentDiff = Math.abs(cardRevenue - docAmount) / Math.max(cardRevenue, docAmount);
        if (percentDiff < 0.2) {
          score += 20;
          matchReasons.push('Revenue amount match');
        }
      }

      // Address/location similarity
      if (extractedData.address && card.customerLocation) {
        const addressSimilarity = calculateStringSimilarity(extractedData.address, card.customerLocation);
        if (addressSimilarity > 0.7) {
          score += 15;
          matchReasons.push('Location match');
        }
      }

      // Project type match
      if (extractedData.projectType && card.tags) {
        const tagMatch = card.tags.some(tag => tag.includes(extractedData.projectType) || extractedData.projectType.includes(tag));
        if (tagMatch) {
          score += 10;
          matchReasons.push('Project type match');
        }
      }

      if (score > highestScore && score > 30) { // Minimum threshold
        highestScore = score;
        bestMatch = {
          ...card,
          matchScore: score,
          matchConfidence: score > 80 ? 'high' : score > 50 ? 'medium' : 'low',
          matchReasons
        };
      }
    });

    return bestMatch;
  };

  // Calculate string similarity using Levenshtein distance
  const calculateStringSimilarity = (str1, str2) => {
    if (!str1 || !str2) return 0;

    const s1 = str1.toLowerCase().trim();
    const s2 = str2.toLowerCase().trim();

    if (s1 === s2) return 1;

    const len1 = s1.length;
    const len2 = s2.length;

    if (len1 === 0) return len2 === 0 ? 1 : 0;
    if (len2 === 0) return 0;

    const matrix = Array(len2 + 1).fill(null).map(() => Array(len1 + 1).fill(null));

    for (let i = 0; i <= len1; i++) matrix[0][i] = i;
    for (let j = 0; j <= len2; j++) matrix[j][0] = j;

    for (let j = 1; j <= len2; j++) {
      for (let i = 1; i <= len1; i++) {
        const indicator = s1[i - 1] === s2[j - 1] ? 0 : 1;
        matrix[j][i] = Math.min(
          matrix[j][i - 1] + 1,
          matrix[j - 1][i] + 1,
          matrix[j - 1][i - 1] + indicator
        );
      }
    }

    const distance = matrix[len2][len1];
    return 1 - distance / Math.max(len1, len2);
  };

  // Generate intelligent comment about extraction
  const generateExtractionComment = (parsedData, filename, category, projectMatch) => {
    const { extractedData, confidence } = parsedData;
    const extractedFields = Object.keys(extractedData).length;

    let comment = `📄 Document "${filename}" analyzed and processed:\n\n`;

    if (extractedFields > 0) {
      comment += `✅ Successfully extracted ${extractedFields} data fields:\n`;

      if (extractedData.customerName) comment += `• Customer: ${extractedData.customerName}\n`;
      if (extractedData.projectTitle) comment += `• Project: ${extractedData.projectTitle}\n`;
      if (extractedData.totalAmount) comment += `• Amount: $${extractedData.totalAmount.toLocaleString()}\n`;
      if (extractedData.jobNumber) comment += `• Job #: ${extractedData.jobNumber}\n`;
      if (extractedData.projectType) comment += `• Type: ${extractedData.projectType}\n`;
      if (extractedData.scheduledDate) comment += `• Scheduled: ${extractedData.scheduledDate}\n`;

      comment += `\n🎯 Confidence Level: ${confidence.toUpperCase()}`;

      if (extractedData.signed) {
        comment += '\n✍️ Document appears to be signed';
      }
      if (extractedData.priority === 'urgent') {
        comment += '\n🚨 Urgent priority detected';
      }
    } else {
      comment += `ℹ️ Document processed but no structured data extracted. Filed as ${category}.`;
    }

    // Add project linking information
    if (projectMatch) {
      comment += `\n\n🔗 Project Link Analysis:`;
      comment += `\n• Found potential match: "${projectMatch.title}"`;
      comment += `\n• Customer: ${projectMatch.customerName}`;
      comment += `\n• Confidence: ${projectMatch.matchConfidence.toUpperCase()}`;
      comment += `\n• Match score: ${projectMatch.matchScore}/100`;

      if (projectMatch.matchReasons.length > 0) {
        comment += `\n• Reasons: ${projectMatch.matchReasons.join(', ')}`;
      }

      if (projectMatch.matchConfidence === 'high') {
        comment += '\n\n✅ High confidence match - consider linking this document to the matched project.';
      } else {
        comment += '\n\n❓ Review suggested match to confirm if documents should be linked.';
      }
    }

    return comment;
  };

  // Basic document scanning function (fallback)
  const scanDocument = (filename, category) => {
    const lowerFilename = filename.toLowerCase();
    let scanResults = {
      category: category,
      confidence: 'medium'
    };

    // Basic pattern matching for document types
    if (category === 'vendorQuote') {
      if (lowerFilename.includes('quote') || lowerFilename.includes('estimate')) {
        scanResults.confidence = 'high';
        scanResults.suggestedStatus = 'Quote Received';
      }
    } else if (category === 'customerQuote') {
      if (lowerFilename.includes('quote') || lowerFilename.includes('proposal')) {
        scanResults.confidence = 'high';
        scanResults.suggestedStatus = 'Quote Sent';
      }
    } else if (category === 'signedQuote') {
      if (lowerFilename.includes('signed') || lowerFilename.includes('executed') || lowerFilename.includes('contract')) {
        scanResults.confidence = 'high';
        scanResults.suggestedStatus = 'Contracted';
      }
    }

    return scanResults;
  };

  const handleDeleteAttachment = (index) => {
    const updatedAttachments = [...(localCard.attachments || [])];
    updatedAttachments.splice(index, 1);
    setLocalCard(prev => ({ ...prev, attachments: updatedAttachments }));
  };

  const handleAddVendorFromList = (vendorId) => {
    const selectedVendor = availableVendors.find(v => v.id === vendorId);
    if (!selectedVendor) return;

    const vendors = localCard.vendors || [];
    // Check if vendor is already added
    if (vendors.some(v => v.id === vendorId)) {
      alert('This vendor is already assigned to the project.');
      return;
    }

    const newVendor = {
      id: vendorId,
      name: selectedVendor.name,
      role: 'Primary',
      contactInfo: selectedVendor.email || selectedVendor.phone || '',
      revenue: '',
      notes: '',
      vendorType: selectedVendor.type
    };
    setLocalCard(prev => ({
      ...prev,
      vendors: [...vendors, newVendor]
    }));
  };

  const handleAddVendor = () => {
    const vendors = localCard.vendors || [];
    const newVendor = {
      id: Date.now(),
      name: '',
      role: 'Primary',
      contactInfo: '',
      revenue: '',
      notes: ''
    };
    setLocalCard(prev => ({
      ...prev,
      vendors: [...vendors, newVendor]
    }));
  };

  const handleUpdateVendor = (vendorId, field, value) => {
    const vendors = localCard.vendors || [];
    const updatedVendors = vendors.map(vendor =>
      vendor.id === vendorId ? { ...vendor, [field]: value } : vendor
    );
    setLocalCard(prev => ({
      ...prev,
      vendors: updatedVendors
    }));
  };

  const handleRemoveVendor = (vendorId) => {
    const vendors = localCard.vendors || [];
    const updatedVendors = vendors.filter(vendor => vendor.id !== vendorId);
    setLocalCard(prev => ({
      ...prev,
      vendors: updatedVendors
    }));
  };

  const handleCrewAssignment = (crewData) => {
    setLocalCard(prev => ({
      ...prev,
      ...crewData
    }));
    setCrewAssignmentOpen(false);
  };

  // Auto-save comments function
  const autoSaveComment = () => {
    if (newComment.trim()) {
      const comments = localCard.comments || [];
      const newCommentEntry = {
        id: Date.now(),
        text: newComment.trim(),
        timestamp: new Date().toISOString(),
        author: 'User' // Could be enhanced with actual user info
      };

      setLocalCard(prev => ({
        ...prev,
        comments: [...comments, newCommentEntry],
        lastComment: newComment.trim(),
        updated: new Date().toISOString()
      }));

      setNewComment('');
    }
  };

  // Handle comment changes - no autosave
  const handleCommentChange = (value) => {
    setNewComment(value);
  };

  // Handle Enter key in comment box
  const handleCommentKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      autoSaveComment();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60">
        <div className="bg-white rounded shadow-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto relative">
          <button
            onClick={closeModal}
            className="absolute top-2 right-2 text-red-500 text-xl font-bold"
          >
            ×
          </button>

          <h2 className="text-lg font-bold mb-4">Edit Card</h2>

          {/* Basic Information */}
          <div className="grid grid-cols-2 gap-4 mb-4">
            <input className="border p-2" value={localCard.title || ""} onChange={e => handleChange("title", e.target.value)} placeholder="Project Title" />
            <input className="border p-2" value={localCard.customerName || ""} onChange={e => handleChange("customerName", e.target.value)} placeholder="Customer Name" />
            <div className="relative">
              <input
                className="border p-2 bg-gray-50 text-gray-700"
                value={localCard.jobNumber || autoGeneratedFields.jobNumber || ""}
                onChange={e => handleChange("jobNumber", e.target.value)}
                placeholder="Auto-generated Project Number"
                title="Format: LocationYearPeriodSequence (e.g., FTW2025P901)"
              />
              <span className="absolute right-2 top-2 text-xs text-gray-500">
                {autoGeneratedFields.jobNumber ? '✨ Auto' : 'Manual'}
              </span>
              {autoGeneratedFields.jobNumber && (
                <button
                  type="button"
                  onClick={() => {
                    setLocalCard(prev => ({ ...prev, jobNumber: autoGeneratedFields.jobNumber }));
                    const comments = localCard.comments || [];
                    const newComment = {
                      id: Date.now(),
                      text: `🔢 Auto-generated job number: ${autoGeneratedFields.jobNumber}`,
                      timestamp: new Date().toISOString(),
                      author: 'System',
                      type: 'auto-generation'
                    };
                    setLocalCard(prev => ({ ...prev, comments: [...comments, newComment] }));
                  }}
                  className="absolute right-8 top-1 text-xs bg-blue-500 text-white px-1 rounded"
                  title="Click to use auto-generated number"
                >
                  Use
                </button>
              )}
            </div>
            <div className="relative">
              <input
                className="border p-2"
                value={localCard.customerLocation || ""}
                onChange={e => handleChange("customerLocation", e.target.value)}
                placeholder="Customer Location/Address"
              />
              {smartSuggestions.customerLocation && !localCard.customerLocation && (
                <button
                  type="button"
                  onClick={() => applySuggestion('customerLocation', smartSuggestions.customerLocation)}
                  className="absolute right-1 top-1 text-xs bg-green-500 text-white px-2 py-1 rounded"
                  title={`Suggested: ${smartSuggestions.customerLocation}`}
                >
                  💡 Use Previous
                </button>
              )}
            </div>
            <select className="border p-2" value={localCard.location || ""} onChange={e => handleChange("location", e.target.value)}>
              <option value="">Select Our Location</option>
              {lanes.map(l => <option key={l.name} value={l.name}>{l.name}</option>)}
            </select>
            <select className="border p-2" value={localCard.status || ""} onChange={e => handleChange("status", e.target.value)}>
              <option value="">Select Status</option>
              {statuses.map(s => <option key={s.name} value={s.name}>{s.name}</option>)}
            </select>
          </div>

          {/* Priority Flag Selection */}
          <div className="mb-4">
            <div className="flex justify-between items-center mb-2">
              <label className="block text-sm font-medium text-gray-700">Priority Flag</label>
              {autoGeneratedFields.priority && (
                <span className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded">
                  ✨ Auto-detected: {autoGeneratedFields.priority}
                </span>
              )}
            </div>
            <div className="flex gap-3 flex-wrap">
              {['None', 'Low', 'Medium', 'High', 'Critical'].map(priority => (
                <label key={priority} className="flex items-center cursor-pointer">
                  <input
                    type="radio"
                    name="priority"
                    value={priority === 'None' ? '' : priority}
                    checked={priority === 'None' ? (!localCard.priority || localCard.priority === '') : localCard.priority === priority}
                    onChange={e => handleChange("priority", e.target.value)}
                    className="mr-2"
                  />
                  <span className={`px-3 py-1 rounded text-sm font-medium ${
                    priority === 'None' ? 'bg-gray-300 text-gray-700' :
                    priority === 'Critical' ? 'bg-red-500 text-white' :
                    priority === 'High' ? 'bg-orange-500 text-white' :
                    priority === 'Medium' ? 'bg-yellow-500 text-white' :
                    'bg-green-500 text-white'
                  }`}>
                    {priority}
                  </span>
                </label>
              ))}
            </div>
          </div>

          {/* Assignment */}
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-1">Assigned To</label>
            <select
              value={localCard.assignedTo || ""}
              onChange={e => handleChange("assignedTo", e.target.value)}
              className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="">Select team member...</option>
              {availablePersonnel.map(person => (
                <option key={person.id} value={`${person.name} - ${person.position}`}>
                  {person.name} - {person.position} {person.location === 'Regional' ? '(Regional)' : ''}
                </option>
              ))}
            </select>
          </div>

          {/* Financial Information */}
          {localCard.status !== 'Lead' && (
            <div className="mb-4">
              <h4 className="font-semibold text-gray-700 mb-2">💰 Financial Information</h4>
              <div className="grid grid-cols-2 gap-4">
                <div className="relative">
                  <input
                    className="border p-2"
                    value={localCard.revenue || ""}
                    onChange={e => handleChange("revenue", e.target.value)}
                    placeholder="Total Revenue ($) - Optional"
                  />
                  {smartSuggestions.revenue && !localCard.revenue && (
                    <button
                      type="button"
                      onClick={() => applySuggestion('revenue', smartSuggestions.revenue)}
                      className="absolute right-1 top-1 text-xs bg-green-500 text-white px-2 py-1 rounded"
                      title={`Avg for this customer: $${smartSuggestions.revenue}`}
                    >
                      💡 ${smartSuggestions.revenue}
                    </button>
                  )}
                </div>
                <div className="relative">
                  <input
                    className="border p-2"
                    value={localCard.vendor || ""}
                    onChange={e => handleChange("vendor", e.target.value)}
                    placeholder="Primary Vendor (Legacy)"
                  />
                  {smartSuggestions.vendor && !localCard.vendor && (
                    <button
                      type="button"
                      onClick={() => applySuggestion('vendor', smartSuggestions.vendor)}
                      className="absolute right-1 top-1 text-xs bg-green-500 text-white px-2 py-1 rounded"
                      title={`Customer's preferred: ${smartSuggestions.vendor}`}
                    >
                      💡 Use Preferred
                    </button>
                  )}
                </div>
              </div>
              {localCard.status && localCard.status.toLowerCase().includes('quoted') && (
                <div className="mt-2">
                  <input
                    className="border p-2 w-full"
                    value={localCard.estimatedPOAmount || ""}
                    onChange={e => handleChange("estimatedPOAmount", e.target.value)}
                    placeholder="Estimated Total PO Amount ($) - Vendor Costs"
                  />
                  <p className="text-xs text-blue-600 mt-1">
                    💼 This is the estimated total purchase order amount for vendor costs (what we'll pay vendors)
                  </p>
                </div>
              )}
              <p className="text-xs text-gray-500 mt-1">
                💡 Revenue is optional until project is quoted. Leads should not have revenue values.
              </p>
            </div>
          )}

          {/* Lead Information Notice */}
          {localCard.status === 'Lead' && (
            <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded">
              <h4 className="font-semibold text-blue-700 mb-1">🔍 Lead Status</h4>
              <p className="text-sm text-blue-600">
                This is a lead - no revenue should be assigned until it becomes a quoted project.
              </p>
            </div>
          )}

          {/* Vendor Management */}
          <div className="mb-4">
            <div className="flex justify-between items-center mb-2">
              <h4 className="font-semibold text-gray-700">🏢 Vendor Management</h4>
              <div className="flex gap-2">
                <select
                  onChange={(e) => {
                    if (e.target.value) {
                      handleAddVendorFromList(e.target.value);
                      e.target.value = ''; // Reset selection
                    }
                  }}
                  className="border p-1 text-sm rounded"
                  defaultValue=""
                >
                  <option value="">Select Vendor</option>
                  {smartSuggestions.recommendedVendors && smartSuggestions.recommendedVendors.length > 0 && (
                    <optgroup label="🌟 Recommended for this location">
                      {smartSuggestions.recommendedVendors.map(vendor => (
                        <option key={vendor.id} value={vendor.id}>
                          ⭐ {vendor.name} ({vendor.type})
                        </option>
                      ))}
                    </optgroup>
                  )}
                  <optgroup label="All Available Vendors">
                    {availableVendors.map(vendor => (
                      <option key={vendor.id} value={vendor.id}>
                        {vendor.name} ({vendor.type})
                      </option>
                    ))}
                  </optgroup>
                </select>
                <button
                  onClick={handleAddVendor}
                  className="bg-gray-500 text-white px-3 py-1 rounded text-sm hover:bg-gray-600"
                  type="button"
                  title="Add custom vendor"
                >
                  + Custom
                </button>
              </div>
            </div>
            {(localCard.vendors || []).map((vendor, index) => (
              <div key={vendor.id} className="border rounded p-3 mb-2 bg-gray-50">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm font-medium text-gray-600">Vendor #{index + 1}</span>
                  <button
                    onClick={() => handleRemoveVendor(vendor.id)}
                    className="text-red-500 text-sm hover:text-red-700"
                    type="button"
                  >
                    Remove
                  </button>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  <input
                    className="border p-2 text-sm"
                    value={vendor.name || ""}
                    onChange={e => handleUpdateVendor(vendor.id, "name", e.target.value)}
                    placeholder="Vendor Name"
                  />
                  <input
                    className="border p-2 text-sm"
                    value={vendor.estimate || ""}
                    onChange={e => handleUpdateVendor(vendor.id, "estimate", e.target.value)}
                    placeholder="Vendor Estimate ($)"
                  />
                  <input
                    className="border p-2 text-sm"
                    value={vendor.poNumber || ""}
                    onChange={e => handleUpdateVendor(vendor.id, "poNumber", e.target.value)}
                    placeholder="PO Number"
                  />
                </div>
              </div>
            ))}
            {(!localCard.vendors || localCard.vendors.length === 0) && (
              <div className="text-gray-500 text-sm italic p-3 border-2 border-dashed border-gray-300 rounded text-center">
                No vendors added yet. Click "+ Add Vendor" to get started.
              </div>
            )}
          </div>



          {/* Intelligent Predictions Panel */}
          {(Object.keys(intelligentSuggestions).length > 0 || !localCard.id) && (
            <div className="mb-4 p-4 bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg">
              <h4 className="font-semibold text-purple-800 mb-3">🤖 AI Insights & Predictions</h4>

              {intelligentSuggestions.estimatedDuration && (
                <div className="mb-3 p-3 bg-white rounded border-l-4 border-blue-400">
                  <div className="flex justify-between items-center">
                    <span className="text-sm font-medium text-gray-700">⏱️ Estimated Duration</span>
                    <span className="text-xs px-2 py-1 bg-blue-100 text-blue-700 rounded">
                      {intelligentSuggestions.estimatedDuration.confidence} confidence
                    </span>
                  </div>
                  <div className="text-lg font-bold text-blue-600">
                    ~{intelligentSuggestions.estimatedDuration.days} days
                  </div>
                  <div className="text-xs text-gray-500">
                    Based on {intelligentSuggestions.estimatedDuration.sampleSize} similar projects
                  </div>
                </div>
              )}

              {intelligentSuggestions.nextMilestone && (
                <div className="mb-3 p-3 bg-white rounded border-l-4 border-green-400">
                  <div className="text-sm font-medium text-gray-700 mb-1">🎯 Next Likely Status</div>
                  <div className="font-bold text-green-600">
                    {intelligentSuggestions.nextMilestone.status}
                  </div>
                  <div className="text-xs text-gray-500">
                    {intelligentSuggestions.nextMilestone.probability}% probability based on similar projects
                  </div>
                </div>
              )}

              {intelligentSuggestions.estimatedRevenue && (
                <div className="mb-3 p-3 bg-white rounded border-l-4 border-yellow-400">
                  <div className="text-sm font-medium text-gray-700 mb-1">💰 Revenue Prediction</div>
                  <div className="font-bold text-yellow-600">
                    ${intelligentSuggestions.estimatedRevenue.estimated.toLocaleString()}
                  </div>
                  <div className="text-xs text-gray-500">
                    Range: ${intelligentSuggestions.estimatedRevenue.range.min.toLocaleString()} -
                    ${intelligentSuggestions.estimatedRevenue.range.max.toLocaleString()}
                  </div>
                  {!localCard.revenue && (
                    <button
                      onClick={() => {
                        setLocalCard(prev => ({
                          ...prev,
                          revenue: intelligentSuggestions.estimatedRevenue.estimated
                        }));
                      }}
                      className="mt-1 text-xs bg-yellow-500 text-white px-2 py-1 rounded hover:bg-yellow-600"
                    >
                      💡 Use Prediction
                    </button>
                  )}
                </div>
              )}

              {intelligentSuggestions.recommendedAssignment && intelligentSuggestions.recommendedAssignment.length > 0 && (
                <div className="mb-3 p-3 bg-white rounded border-l-4 border-indigo-400">
                  <div className="text-sm font-medium text-gray-700 mb-2">👤 Recommended Assignment</div>
                  <div className="space-y-1">
                    {intelligentSuggestions.recommendedAssignment.slice(0, 2).map((rec, idx) => (
                      <div key={idx} className="flex justify-between items-center text-xs">
                        <span className="font-medium text-indigo-600">{rec.person}</span>
                        <div className="flex gap-2 text-gray-500">
                          <span>{rec.completionRate}% completion</span>
                          <span>{rec.avgDuration}d avg</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {intelligentSuggestions.potentialRisks && intelligentSuggestions.potentialRisks.length > 0 && (
                <div className="mb-3 p-3 bg-white rounded border-l-4 border-red-400">
                  <div className="text-sm font-medium text-gray-700 mb-2">⚠️ Potential Risks</div>
                  <div className="space-y-1">
                    {intelligentSuggestions.potentialRisks.map((risk, idx) => (
                      <div key={idx} className="text-xs">
                        <span className={`inline-block w-2 h-2 rounded-full mr-2 ${
                          risk.severity === 'high' ? 'bg-red-500' :
                          risk.severity === 'medium' ? 'bg-yellow-500' : 'bg-blue-500'
                        }`}></span>
                        <span className="text-gray-700">{risk.message}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {intelligentSuggestions.suggestedVendors && intelligentSuggestions.suggestedVendors.length > 0 && (
                <div className="p-3 bg-white rounded border-l-4 border-green-400">
                  <div className="text-sm font-medium text-gray-700 mb-2">🏢 Frequently Used Vendors</div>
                  <div className="flex gap-2 flex-wrap">
                    {intelligentSuggestions.suggestedVendors.map((vendor, idx) => (
                      <button
                        key={idx}
                        onClick={() => {
                          // Auto-add vendor if not already present
                          const existingVendors = localCard.vendors || [];
                          if (!existingVendors.some(v => v.name === vendor.name)) {
                            const newVendor = {
                              id: Date.now() + idx,
                              name: vendor.name,
                              role: 'Primary',
                              contactInfo: '',
                              revenue: '',
                              notes: 'Added via AI suggestion'
                            };
                            setLocalCard(prev => ({
                              ...prev,
                              vendors: [...existingVendors, newVendor]
                            }));
                          }
                        }}
                        className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded hover:bg-green-200"
                        title={`Used in ${vendor.frequency} similar projects`}
                      >
                        + {vendor.name}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Industry Insights for New Projects */}
              {intelligentSuggestions.industryInsights && (
                <div className="space-y-3">
                  {intelligentSuggestions.industryInsights.suggestedDuration && (
                    <div className="p-3 bg-white rounded border-l-4 border-cyan-400">
                      <div className="text-sm font-medium text-gray-700 mb-1">📅 Industry Standard Duration</div>
                      <div className="text-cyan-600 font-semibold">
                        {intelligentSuggestions.industryInsights.suggestedDuration.min}-{intelligentSuggestions.industryInsights.suggestedDuration.max} {intelligentSuggestions.industryInsights.suggestedDuration.unit}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">Based on similar environmental projects</div>
                    </div>
                  )}

                  {intelligentSuggestions.industryInsights.budgetRange && (
                    <div className="p-3 bg-white rounded border-l-4 border-amber-400">
                      <div className="text-sm font-medium text-gray-700 mb-1">💰 Typical Budget Range</div>
                      <div className="text-amber-600 font-semibold">
                        ${intelligentSuggestions.industryInsights.budgetRange.min.toLocaleString()} - ${intelligentSuggestions.industryInsights.budgetRange.max.toLocaleString()}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">Industry benchmarks for similar work</div>
                    </div>
                  )}

                  {intelligentSuggestions.industryInsights.commonChallenges.length > 0 && (
                    <div className="p-3 bg-white rounded border-l-4 border-orange-400">
                      <div className="text-sm font-medium text-gray-700 mb-2">⚠️ Common Challenges</div>
                      <div className="space-y-1">
                        {intelligentSuggestions.industryInsights.commonChallenges.map((challenge, idx) => (
                          <div key={idx} className="text-xs text-gray-600">• {challenge}</div>
                        ))}
                      </div>
                    </div>
                  )}

                  {intelligentSuggestions.industryInsights.requiredPermits.length > 0 && (
                    <div className="p-3 bg-white rounded border-l-4 border-indigo-400">
                      <div className="text-sm font-medium text-gray-700 mb-2">📋 Typical Permits Required</div>
                      <div className="space-y-1">
                        {intelligentSuggestions.industryInsights.requiredPermits.map((permit, idx) => (
                          <div key={idx} className="text-xs text-gray-600">• {permit}</div>
                        ))}
                      </div>
                    </div>
                  )}

                  {intelligentSuggestions.industryInsights.safetyConsiderations.length > 0 && (
                    <div className="p-3 bg-white rounded border-l-4 border-red-400">
                      <div className="text-sm font-medium text-gray-700 mb-2">🛡️ Safety Considerations</div>
                      <div className="space-y-1">
                        {intelligentSuggestions.industryInsights.safetyConsiderations.map((safety, idx) => (
                          <div key={idx} className="text-xs text-gray-600">• {safety}</div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Getting Started Tips for New Cards */}
              {(!localCard.id || (Object.keys(intelligentSuggestions).length === 1 && intelligentSuggestions.industryInsights)) && (
                <div className="p-3 bg-white rounded border-l-4 border-blue-400">
                  <div className="text-sm font-medium text-gray-700 mb-2">💡 Smart Tips</div>
                  <div className="space-y-2 text-xs text-gray-600">
                    <div>• Fill in customer name and project title for personalized suggestions</div>
                    <div>• Select a location to get vendor recommendations</div>
                    <div>• Add project keywords for automated priority detection</div>
                    <div>• Create more projects to unlock AI predictions and insights</div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Tags */}
          <div className="mb-4">
            <h4 className="font-semibold text-gray-700 mb-2">🏷️ Tags</h4>
            <input
              className="border p-2 w-full"
              value={(localCard.tags || []).join(', ')}
              onChange={e => handleChange("tags", e.target.value.split(',').map(t => t.trim()).filter(t => t))}
              placeholder="e.g., hazardous, urgent, lab-pack (comma separated)"
            />
          </div>

          <textarea className="border p-2 w-full mt-4" value={localCard.description || ""} onChange={e => handleChange("description", e.target.value)} placeholder="Description" rows={4} />

          {/* Milestone Tracking */}
          <div className="mt-4 border-t pt-4">
            <h4 className="font-semibold text-gray-700 mb-3">📅 Milestone Tracking</h4>
            <div className="flex gap-4">
              <div className="flex-1">
                <select
                  className="border p-2 w-full text-sm mb-2"
                  onChange={(e) => {
                    const milestoneType = e.target.value;
                    if (milestoneType) {
                      document.getElementById('milestone-date-input').focus();
                      setLocalCard(prev => ({ ...prev, pendingMilestone: milestoneType }));
                    }
                  }}
                  value=""
                >
                  <option value="">Select milestone type...</option>
                  <option value="dateReceived">Date Received</option>
                  <option value="quoteSent">Quote Sent</option>
                  <option value="dateScheduled">Date Scheduled</option>
                  <option value="dateComplete">Date Complete</option>
                </select>
                <input
                  id="milestone-date-input"
                  type="date"
                  className="border p-2 w-full text-sm"
                  onChange={e => {
                    const milestoneType = localCard.pendingMilestone || 'dateReceived';
                    const timeline = { ...localCard.statusTimeline };
                    timeline[milestoneType] = e.target.value ? new Date(e.target.value).toISOString() : '';

                    // Add automated comment
                    const comments = localCard.comments || [];
                    const milestoneLabels = {
                      dateReceived: 'Date Received',
                      quoteSent: 'Quote Sent',
                      dateScheduled: 'Date Scheduled',
                      dateComplete: 'Date Complete'
                    };

                    // Auto-update status based on milestone
                    let newStatus = localCard.status;
                    let statusChanged = false;

                    if (e.target.value) {
                      // Automatic status changes based on milestones
                      if (milestoneType === 'quoteSent' && localCard.status === 'Lead') {
                        const quotedStatus = statuses.find(s => s.name.toLowerCase().includes('quoted'));
                        if (quotedStatus) {
                          newStatus = quotedStatus.name;
                          statusChanged = true;
                        }
                      } else if (milestoneType === 'dateScheduled') {
                        const scheduledStatus = statuses.find(s =>
                          s.name.toLowerCase().includes('scheduled') ||
                          s.name.toLowerCase().includes('active') ||
                          s.name.toLowerCase().includes('contracted')
                        );
                        if (scheduledStatus) {
                          newStatus = scheduledStatus.name;
                          statusChanged = true;
                        }
                      } else if (milestoneType === 'dateComplete') {
                        const completeStatus = statuses.find(s =>
                          s.name.toLowerCase().includes('complete') ||
                          s.name.toLowerCase().includes('finished') ||
                          s.name.toLowerCase().includes('done')
                        );
                        if (completeStatus) {
                          newStatus = completeStatus.name;
                          statusChanged = true;
                        }
                      }

                      const newComment = {
                        id: Date.now(),
                        text: `📅 ${milestoneLabels[milestoneType]} set to ${new Date(e.target.value).toLocaleDateString()}${statusChanged ? ` → Status auto-updated to "${newStatus}"` : ''}`,
                        timestamp: new Date().toISOString(),
                        author: 'System',
                        type: 'milestone'
                      };

                      // Update status history if status changed
                      let updatedStatusHistory = localCard.statusHistory || [];
                      if (statusChanged) {
                        const statusEntry = {
                          status: newStatus,
                          timestamp: new Date().toISOString(),
                          previousStatus: localCard.status,
                          automatedBy: `${milestoneLabels[milestoneType]} milestone`
                        };
                        updatedStatusHistory = [...updatedStatusHistory, statusEntry];
                      }

                      setLocalCard(prev => ({
                        ...prev,
                        status: newStatus,
                        statusTimeline: timeline,
                        statusHistory: updatedStatusHistory,
                        comments: [...comments, newComment],
                        pendingMilestone: null,
                        updated: new Date().toISOString()
                      }));
                    }
                  }}
                />
              </div>
              <div className="text-xs text-gray-500 pt-2">
                {localCard.statusTimeline && (
                  <div className="space-y-1">
                    {localCard.statusTimeline.dateReceived && (
                      <div>✅ Received: {new Date(localCard.statusTimeline.dateReceived).toLocaleDateString()}</div>
                    )}
                    {localCard.statusTimeline.quoteSent && (
                      <div>✅ Quote Sent: {new Date(localCard.statusTimeline.quoteSent).toLocaleDateString()}</div>
                    )}
                    {localCard.statusTimeline.dateScheduled && (
                      <div>✅ Scheduled: {new Date(localCard.statusTimeline.dateScheduled).toLocaleDateString()}</div>
                    )}
                    {localCard.statusTimeline.dateComplete && (
                      <div>✅ Completed: {new Date(localCard.statusTimeline.dateComplete).toLocaleDateString()}</div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Comments Section */}
          <div className="mt-4 border-t pt-4">
            <h4 className="font-semibold text-gray-700 mb-3">💬 Comments</h4>

            {/* Existing Comments */}
            {localCard.comments && localCard.comments.length > 0 && (
              <div className="max-h-40 overflow-y-auto mb-3 space-y-2">
                {localCard.comments.slice().reverse().map((comment, index) => (
                  <div key={comment.id || index} className="text-sm p-3 bg-gray-50 rounded border-l-4 border-blue-400">
                    <div className="font-medium text-gray-800">{comment.text}</div>
                    <div className="text-xs text-gray-500 mt-1">
                      {comment.author} • {new Date(comment.timestamp).toLocaleDateString()} {new Date(comment.timestamp).toLocaleTimeString()}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* New Comment Input */}
            <div>
              <textarea
                className="border p-2 w-full text-sm"
                value={newComment}
                onChange={e => handleCommentChange(e.target.value)}
                onKeyDown={handleCommentKeyDown}
                placeholder="Add a comment... (Press Enter to save, Shift+Enter for new line)"
                rows={3}
              />
              <div className="flex justify-between items-center mt-1">
                <span className="text-xs text-gray-500">
                  Press Enter to save, or use button →
                </span>
                <button
                  onClick={autoSaveComment}
                  className="px-3 py-1 text-sm bg-blue-600 text-white rounded hover:bg-blue-700"
                  disabled={!newComment.trim()}
                >
                  Save Comment
                </button>
              </div>
            </div>
          </div>

          {/* Status History */}
          {(localCard.statusHistory && localCard.statusHistory.length > 0) && (
            <div className="mt-4 border-t pt-4">
              <h4 className="font-semibold text-gray-700 mb-2">📈 Status History</h4>
              <div className="max-h-32 overflow-y-auto">
                {localCard.statusHistory.slice().reverse().map((entry, index) => (
                  <div key={index} className="text-sm p-2 bg-gray-50 border-l-4 border-blue-400 mb-1">
                    <div className="flex justify-between">
                      <span className="font-medium">{entry.previousStatus} → {entry.status}</span>
                      <span className="text-gray-500">
                        {new Date(entry.timestamp).toLocaleDateString()} {new Date(entry.timestamp).toLocaleTimeString()}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Project Link Suggestions */}
          {localCard.suggestedProjectLink && (
            <div className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
              <h4 className="font-semibold text-yellow-800 mb-2">🔗 Document-Project Link Detected</h4>
              <div className="text-sm text-yellow-700 mb-3">
                This document appears to belong to another project:
              </div>
              <div className="bg-white p-3 rounded border border-yellow-300 mb-3">
                <div className="font-medium text-gray-800">{localCard.suggestedProjectLink.projectTitle}</div>
                <div className="text-sm text-gray-600">Customer: {localCard.suggestedProjectLink.customerName}</div>
                <div className="text-xs text-gray-500 mt-1">
                  Confidence: {localCard.suggestedProjectLink.confidence.toUpperCase()}
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    // In a real app, this would navigate to the linked project
                    alert(`Would navigate to project: ${localCard.suggestedProjectLink.projectTitle}`);
                  }}
                  className="px-3 py-1 text-sm bg-blue-500 text-white rounded hover:bg-blue-600"
                >
                  🔗 View Linked Project
                </button>
                <button
                  onClick={() => {
                    // Move document to the suggested project
                    alert(`Would move document to project: ${localCard.suggestedProjectLink.projectTitle}`);
                  }}
                  className="px-3 py-1 text-sm bg-green-500 text-white rounded hover:bg-green-600"
                >
                  📦 Move Document
                </button>
                <button
                  onClick={() => {
                    setLocalCard(prev => {
                      const { suggestedProjectLink, ...rest } = prev;
                      return rest;
                    });
                  }}
                  className="px-3 py-1 text-sm bg-gray-500 text-white rounded hover:bg-gray-600"
                >
                  ❌ Dismiss
                </button>
              </div>
            </div>
          )}

          {/* Document Upload */}
          <div className="mt-6 border-t pt-4">
            <h4 className="font-semibold text-gray-700 mb-3">📄 Document Upload</h4>
            <div className="flex gap-2">
              <select
                className="border p-2 text-sm"
                value={localCard.pendingDocumentType || 'general'}
                onChange={(e) => setLocalCard(prev => ({ ...prev, pendingDocumentType: e.target.value }))}
              >
                <option value="general">General Document</option>
                <option value="vendorQuote">🏢 Vendor Quote</option>
                <option value="customerQuote">📋 Customer Quote</option>
                <option value="signedQuote">✅ Signed Quote</option>
                <option value="invoice">💳 Invoice</option>
                <option value="manifest">📦 Manifest</option>
                <option value="receipt">🧾 Receipt</option>
              </select>
              <input
                type="file"
                onChange={(e) => {
                  const documentType = localCard.pendingDocumentType || 'general';
                  handleCategorizedFileUpload(e, documentType);

                  // Add automated comment for file upload
                  const files = Array.from(e.target.files);
                  if (files.length > 0) {
                    const comments = localCard.comments || [];
                    const typeLabels = {
                      vendorQuote: 'Vendor Quote',
                      customerQuote: 'Customer Quote',
                      signedQuote: 'Signed Quote',
                      invoice: 'Invoice',
                      manifest: 'Manifest',
                      receipt: 'Receipt',
                      general: 'Document'
                    };

                    files.forEach(file => {
                      const newComment = {
                        id: Date.now() + Math.random(),
                        text: `📎 ${typeLabels[documentType]} uploaded: ${file.name}`,
                        timestamp: new Date().toISOString(),
                        author: 'System',
                        type: 'document'
                      };

                      setLocalCard(prev => ({
                        ...prev,
                        comments: [...(prev.comments || []), newComment]
                      }));
                    });
                  }
                }}
                className="flex-1 text-sm"
                accept=".pdf,.doc,.docx,.jpg,.png,.csv,.txt"
                multiple
              />
            </div>
            <p className="text-xs text-gray-500 mt-2">
              🤖 AI will automatically extract data and suggest project links
            </p>
            <div className="text-xs text-blue-600 mt-1">
              Supported: Text files, CSV, PDFs, Images with text content
            </div>
          </div>

          {/* Attachments Section */}
          {localCard.attachments && localCard.attachments.length > 0 && (
            <div className="mt-4 border-t pt-4">
              <h3 className="text-md font-semibold mb-2">Attached Files</h3>
              <ul className="space-y-2">
                {localCard.attachments.map((file, idx) => (
                  <li key={idx} className="flex justify-between items-center">
                    <span className="truncate max-w-xs">{file.name}</span>
                    <div className="space-x-2">
                      <a href={file.url} download={file.name} className="text-blue-600 underline text-sm">Download</a>
                      <button onClick={() => handleDeleteAttachment(idx)} className="text-red-500 text-sm">Remove</button>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Crew Assignment Section */}
          <div className="mt-4 border-t pt-4">
            <h4 className="font-semibold text-gray-700 mb-2">👥 Crew Assignment</h4>
            {localCard.assignedCrew && localCard.assignedCrew.length > 0 ? (
              <div className="space-y-1 mb-3">
                {localCard.assignedCrew.map((member, index) => (
                  <div key={index} className="text-sm bg-blue-50 p-2 rounded border">
                    {member}
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-sm text-gray-500 mb-3 p-2 bg-gray-50 rounded border-dashed border-2">
                No crew assigned yet
              </div>
            )}

            {localCard.equipmentNeeded && (
              <div className="mt-2">
                <span className="text-sm font-medium text-gray-600">Equipment: </span>
                <span className="text-sm text-gray-700">{localCard.equipmentNeeded}</span>
              </div>
            )}
            {localCard.crewNotes && (
              <div className="mt-1">
                <span className="text-sm font-medium text-gray-600">Notes: </span>
                <span className="text-sm text-gray-700">{localCard.crewNotes}</span>
              </div>
            )}
            <button
              onClick={() => setCrewAssignmentOpen(true)}
              className="mt-2 text-sm text-blue-600 hover:text-blue-800 underline"
            >
              {localCard.assignedCrew && localCard.assignedCrew.length > 0 ? 'Edit Crew Assignment' : 'Assign Crew'}
            </button>
          </div>

          <div className="mt-6 flex justify-end space-x-2">
            <button onClick={handleSave} className="bg-blue-500 text-white px-4 py-2 rounded">Save</button>
            <button onClick={closeModal} className="bg-gray-300 text-black px-4 py-2 rounded">Cancel</button>
          </div>
        </div>

        {/* Crew Assignment Modal */}
        <CrewAssignmentModal
          isOpen={crewAssignmentOpen}
          onClose={() => setCrewAssignmentOpen(false)}
          onSave={handleCrewAssignment}
          card={localCard}
          scheduledDate={pendingScheduledDate || localCard.scheduledDate}
        />
      </div>
  );
}